import type { FontEntry } from './fontshare';

export const FONTSHARE_CATALOG_SNAPSHOT: FontEntry[] = [
  { slug: 'aktura', name: 'Aktura', category: 'sans', fallback: 'sans-serif' },
  { slug: 'alpino', name: 'Alpino', category: 'sans', fallback: 'sans-serif' },
  { slug: 'amulya', name: 'Amulya', category: 'sans', fallback: 'sans-serif' },
  { slug: 'anton', name: 'Anton', category: 'sans', fallback: 'sans-serif' },
  { slug: 'archivo', name: 'Archivo', category: 'sans', fallback: 'sans-serif' },
  { slug: 'array', name: 'Array', category: 'display', fallback: 'sans-serif' },
  { slug: 'asap', name: 'Asap', category: 'sans', fallback: 'sans-serif' },
  { slug: 'author', name: 'Author', category: 'sans', fallback: 'sans-serif' },
  { slug: 'azeret-mono', name: 'Azeret Mono', category: 'sans', fallback: 'sans-serif' },
  { slug: 'beVietnam-pro', name: 'Be Vietnam Pro', category: 'sans', fallback: 'sans-serif' },
  { slug: 'bebas-neue', name: 'Bebas Neue', category: 'sans', fallback: 'sans-serif' },
  { slug: 'bespoke-sans', name: 'Bespoke Sans', category: 'sans', fallback: 'sans-serif' },
  { slug: 'bespoke-serif', name: 'Bespoke Serif', category: 'serif', fallback: 'serif' },
  { slug: 'bespoke-slab', name: 'Bespoke Slab', category: 'sans', fallback: 'sans-serif' },
  { slug: 'bespoke-stencil', name: 'Bespoke Stencil', category: 'sans', fallback: 'sans-serif' },
  { slug: 'bevellier', name: 'Bevellier', category: 'display', fallback: 'sans-serif' },
  { slug: 'bonny', name: 'Bonny', category: 'serif', fallback: 'serif' },
  { slug: 'boska', name: 'Boska', category: 'sans', fallback: 'sans-serif' },
  { slug: 'boxing', name: 'Boxing', category: 'display', fallback: 'sans-serif' },
  { slug: 'britney', name: 'Britney', category: 'sans', fallback: 'sans-serif' },
  { slug: 'cabinet-grotesk', name: 'Cabinet Grotesk', category: 'sans', fallback: 'sans-serif' },
  { slug: 'chillax', name: 'Chillax', category: 'sans', fallback: 'sans-serif' },
  { slug: 'chubbo', name: 'Chubbo', category: 'display', fallback: 'sans-serif' },
  { slug: 'clash-display', name: 'Clash Display', category: 'sans', fallback: 'sans-serif' },
  { slug: 'clash-grotesk', name: 'Clash Grotesk', category: 'sans', fallback: 'sans-serif' },
  { slug: 'comico', name: 'Comico', category: 'display', fallback: 'sans-serif' },
  { slug: 'crimson-pro', name: 'Crimson Pro', category: 'serif', fallback: 'serif' },
  { slug: 'dancing-script', name: 'Dancing Script', category: 'sans', fallback: 'sans-serif' },
  { slug: 'epilogue', name: 'Epilogue', category: 'sans', fallback: 'sans-serif' },
  { slug: 'erode', name: 'Erode', category: 'serif', fallback: 'serif' },
  { slug: 'excon', name: 'Excon', category: 'sans', fallback: 'sans-serif' },
  { slug: 'expose', name: 'Expose', category: 'sans', fallback: 'sans-serif' },
  { slug: 'familjen-grotesk', name: 'Familjen Grotesk', category: 'sans', fallback: 'sans-serif' },
  { slug: 'fira-sans', name: 'Fira Sans', category: 'sans', fallback: 'sans-serif' },
  { slug: 'gambarino', name: 'Gambarino', category: 'serif', fallback: 'serif' },
  { slug: 'gambetta', name: 'Gambetta', category: 'serif', fallback: 'serif' },
  { slug: 'general-sans', name: 'General Sans', category: 'sans', fallback: 'sans-serif' },
  { slug: 'hind', name: 'Hind', category: 'sans', fallback: 'sans-serif' },
  { slug: 'hoover', name: 'Hoover', category: 'sans', fallback: 'sans-serif' },
  { slug: 'jet-brains-mono', name: 'JetBrains Mono', category: 'sans', fallback: 'sans-serif' },
  { slug: 'kalam', name: 'Kalam', category: 'display', fallback: 'sans-serif' },
  { slug: 'karma', name: 'Karma', category: 'serif', fallback: 'serif' },
  { slug: 'khand', name: 'Khand', category: 'sans', fallback: 'sans-serif' },
  { slug: 'kihim', name: 'Kihim', category: 'display', fallback: 'sans-serif' },
  { slug: 'kohinoor-zerone', name: 'Kohinoor Zerone', category: 'display', fallback: 'sans-serif' },
  { slug: 'kola', name: 'Kola', category: 'display', fallback: 'sans-serif' },
  { slug: 'literata', name: 'Literata', category: 'serif', fallback: 'serif' },
  { slug: 'lora', name: 'Lora', category: 'serif', fallback: 'serif' },
  { slug: 'manrope', name: 'Manrope', category: 'sans', fallback: 'sans-serif' },
  { slug: 'melodrama', name: 'Melodrama', category: 'sans', fallback: 'sans-serif' },
  { slug: 'merriweather-sans', name: 'Merriweather Sans', category: 'sans', fallback: 'sans-serif' },
  { slug: 'montserrat', name: 'Montserrat', category: 'sans', fallback: 'sans-serif' },
  { slug: 'neco', name: 'Neco', category: 'serif', fallback: 'serif' },
  { slug: 'new-title', name: 'New Title', category: 'sans', fallback: 'sans-serif' },
  { slug: 'nippo', name: 'Nippo', category: 'display', fallback: 'sans-serif' },
  { slug: 'nunito', name: 'Nunito', category: 'sans', fallback: 'sans-serif' },
  { slug: 'oswald', name: 'Oswald', category: 'sans', fallback: 'sans-serif' },
  { slug: 'outfit', name: 'Outfit', category: 'sans', fallback: 'sans-serif' },
  { slug: 'pally', name: 'Pally', category: 'sans', fallback: 'sans-serif' },
  { slug: 'panchang', name: 'Panchang', category: 'sans', fallback: 'sans-serif' },
  { slug: 'paquito', name: 'Paquito', category: 'sans', fallback: 'sans-serif' },
  { slug: 'pencerio', name: 'Pencerio', category: 'sans', fallback: 'sans-serif' },
  { slug: 'pilcrow-rounded', name: 'Pilcrow Rounded', category: 'sans', fallback: 'sans-serif' },
  { slug: 'plein', name: 'Plein', category: 'sans', fallback: 'sans-serif' },
  { slug: 'plus-jakarta-sans', name: 'Plus Jakarta Sans', category: 'sans', fallback: 'sans-serif' },
  { slug: 'poppins', name: 'Poppins', category: 'sans', fallback: 'sans-serif' },
  { slug: 'pramukh-rounded', name: 'Pramukh Rounded', category: 'sans', fallback: 'sans-serif' },
  { slug: 'public-sans', name: 'Public Sans', category: 'sans', fallback: 'sans-serif' },
  { slug: 'quicksand', name: 'Quicksand', category: 'sans', fallback: 'sans-serif' },
  { slug: 'quilon', name: 'Quilon', category: 'sans', fallback: 'sans-serif' },
  { slug: 'rajdhani', name: 'Rajdhani', category: 'sans', fallback: 'sans-serif' },
  { slug: 'ranade', name: 'Ranade', category: 'sans', fallback: 'sans-serif' },
  { slug: 'recia', name: 'Recia', category: 'serif', fallback: 'serif' },
  { slug: 'red-hat-display', name: 'Red Hat Display', category: 'sans', fallback: 'sans-serif' },
  { slug: 'rosaline', name: 'Rosaline', category: 'sans', fallback: 'sans-serif' },
  { slug: 'roundo', name: 'Roundo', category: 'sans', fallback: 'sans-serif' },
  { slug: 'rowan', name: 'Rowan', category: 'serif', fallback: 'serif' },
  { slug: 'rx-100', name: 'RX100', category: 'sans', fallback: 'sans-serif' },
  { slug: 'satoshi', name: 'Satoshi', category: 'sans', fallback: 'sans-serif' },
  { slug: 'segment', name: 'Segment', category: 'display', fallback: 'sans-serif' },
  { slug: 'sentient', name: 'Sentient', category: 'serif', fallback: 'serif' },
  { slug: 'sharpie', name: 'Sharpie', category: 'display', fallback: 'sans-serif' },
  { slug: 'sora', name: 'Sora', category: 'sans', fallback: 'sans-serif' },
  { slug: 'space-grotesk', name: 'Space Grotesk', category: 'sans', fallback: 'sans-serif' },
  { slug: 'spline-sans', name: 'Spline Sans', category: 'sans', fallback: 'sans-serif' },
  { slug: 'stardom', name: 'Stardom', category: 'display', fallback: 'sans-serif' },
  { slug: 'striper', name: 'Striper', category: 'display', fallback: 'sans-serif' },
  { slug: 'styro', name: 'Styro', category: 'display', fallback: 'sans-serif' },
  { slug: 'supreme', name: 'Supreme', category: 'sans', fallback: 'sans-serif' },
  { slug: 'switzer', name: 'Switzer', category: 'sans', fallback: 'sans-serif' },
  { slug: 'synonym', name: 'Synonym', category: 'sans', fallback: 'sans-serif' },
  { slug: 'tabular', name: 'Tabular', category: 'sans', fallback: 'sans-serif' },
  { slug: 'tanker', name: 'Tanker', category: 'sans', fallback: 'sans-serif' },
  { slug: 'technor', name: 'Technor', category: 'sans', fallback: 'sans-serif' },
  { slug: 'teko', name: 'Teko', category: 'sans', fallback: 'sans-serif' },
  { slug: 'telma', name: 'Telma', category: 'sans', fallback: 'sans-serif' },
  { slug: 'trench-slab', name: 'Trench Slab', category: 'sans', fallback: 'sans-serif' },
  { slug: 'work-sans', name: 'Work Sans', category: 'sans', fallback: 'sans-serif' },
  { slug: 'zina', name: 'Zina', category: 'display', fallback: 'sans-serif' },
  { slug: 'zodiak', name: 'Zodiak', category: 'serif', fallback: 'serif' },
];
